Better field size requirement for wraparound check
junyechen1996/draft-chen-cfrg-vdaf-pine pull request #82
Opened 2024-04-29 17:05 UTC by junyechen1996

2024-04-29 17:07 UTC, junyechen1996 commented on poc/find_wr_params.sage
> +    for num_frac_bits in [14, 20, 24]:
Decreasing it since it gives the same number of decimal digits as `num_frac_bits = 15`.

2024-04-29 17:07 UTC, junyechen1996 commented on poc/find_wr_params.sage
> +max_num_clients = 100_000
Decreasing it so that `Field32` could theoretically work.

2024-04-30 00:27 UTC, cjpatton commented on poc/flp_pine.py
>          if (self.Field.MODULUS / num_wr_checks <= 2 or
Don't forget to update the comment above.

2024-04-30 18:24 UTC, cjpatton requested changes

2024-04-30 18:24 UTC, cjpatton commented on poc/flp_pine.py
> +                self.wr_check_bound.as_unsigned() <= 1/4000)):
I'm not sure the math is correct. Expressing things in terms of $\alpha$ and the bound $B$, we want:
$q \geq \frac{B \alpha^2}{4000}$, $q \geq 2600 \alpha \sqrt{B}$, and $q \geq 2r$.

2024-05-01 11:55 UTC, junyechen1996 commented on poc/flp_pine.py
> +                self.wr_check_bound.as_unsigned() <= 1/4000)):
Updated comments. I believe this is correct, so we fail if either fails:

- q / num_wr_checks <= 2
- q / wr_check_bound <= 2600
- q / wr_check_bound / wr_check_bound <= 1/4000

2024-05-01 15:13 UTC, cjpatton commented on poc/flp_pine.py
> +                self.wr_check_bound.as_unsigned() <= 1/4000)):
Oh I see. I missed the $q \geq 2r$ check above. 

Let's see if we can simplify this a bit. 

First, ideally we would do this computation in a way that doesn't require floating point arithmetic. Is it possible to rearange the inequalities such that the arithmetic is over integers?

Second, `q / wr_check_bound**2` is much more readable than `q / wr_check_bound / wr_check_bound`.

2024-05-08 18:29 UTC, cjpatton approved these changes

2024-05-08 18:29 UTC, cjpatton commented on poc/wr_bound
You probably didn't meant to check in this file.

2024-05-08 19:32 UTC, junyechen1996 commented on poc/wr_bound
Yes I didn't... Removed it.

2024-05-08 19:33 UTC, junyechen1996 commented on poc/flp_pine.py
> +                self.wr_check_bound.as_unsigned() <= 1/4000)):
Makes sense. I re-arranged it:

```
if (self.Field.MODULUS / num_wr_checks < 2 or
            self.Field.MODULUS / self.wr_check_bound.as_unsigned() < 2600 or
            self.wr_check_bound.as_unsigned()**2 / self.Field.MODULUS > 4000):
```

My only concern is `self.wr_check_bound.as_unsigned()**2` overflows with this re-arrangement, that's why I opted for division instead of multiplication.

2024-05-08 19:34 UTC, junyechen1996 commented
Sorry @cjpatton the email notification slipped and I didn't address your comments completely. Please take a look at this thread again: https://github.com/junyechen1996/draft-chen-cfrg-vdaf-pine/pull/82#discussion_r1585306536. Thanks.

2024-05-08 19:41 UTC, cjpatton commented on poc/flp_pine.py
> +                self.wr_check_bound.as_unsigned() <= 1/4000)):
Works for me!

2024-05-08 20:40 UTC, junyechen1996 commented
Will merge it once the new version of the paper is officially on arxiv.

2024-06-11 22:47 UTC, merged